[package]
name = "neovim-lib"
version = "0.6.0"
authors = ["daa84 <daa84@inbox.ru>"]
license = "LGPL-3.0"
description = "msgpack-rpc neovim client"
documentation = "https://docs.rs/neovim-lib"
repository = "https://github.com/daa84/neovim-lib"
readme = "README.md"
categories = ["api-bindings"]
keywords = ["neovim"]
exclude = ["generate.bat", "Makefile"]
edition = "2018"

[badges]
travis-ci = { repository = "daa84/neovim-lib", branch = "master"  }

[lib]
bench = false

[dependencies]
rmp = "0.8"
rmpv = { version ="0.4", features=["with-serde"] }
log = "0.4"
#async-std = { version = "1.1.0", features = ["unstable"] }
tokio = { version = "0.2.3", features = ["sync", "rt-core", "macros", "io-util", "tcp", "uds", "process", "io-std", "dns", "rt-threaded", "io-driver"] }
async-trait = "0.1.18"

[target.'cfg(unix)'.dependencies]
unix_socket = "0.5.0"

[dev-dependencies]
tempdir = "0.3"
criterion = "0.3.0"

[profile.bench]
lto = true
debug = true

[[bench]]
name = "rpc"
harness = false
